trigger: none
  # branches:
  # include
  #  - main
  #  - features/*
stages: 
#################################
# Pre Commit - Liniting
###################################
  - stage: PreCommit
    jobs:
    - job: SAST
      displayName: Static Analysis Stage
      pool: Default
      continueOnError: true  # only for dev environment.
      steps:
      - task: tfsec@1
        inputs:
          version: 'v1.26.0'
#################################
# Terraform Install and Plan
###################################
  - stage: Install
    jobs:
    - job: terraformInstall
      displayName: Plan and review stage
      pool: Default
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/enviroments/dev'
          backendServiceArm: 'sp3'
          backendAzureRmStorageAccountName: 'pipelinestgaqs'
          backendAzureRmContainerName: 'tfstatecontainer'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/enviroments/dev'
        
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/enviroments/dev'
          environmentServiceNameAzureRM: 'sp3'
#################################
# Cost and Impact Assement Stage
###################################

  - stage: FinOps
    jobs:
    - job: infraCost
      displayName: Cost & Impact Assessment stage
      pool: Default
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/enviroments/dev'
          backendServiceArm: 'sp3'
          backendAzureRmStorageAccountName: 'pipelinestgaqs'
          backendAzureRmContainerName: 'tfstatecontainer'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/enviroments/dev'
          environmentServiceNameAzureRM: 'sp3'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'infracost breakdown --path C:\Users\chand\OneDrive\Desktop\Tools\agent\_work\5\s\enviroments\dev'
#################################
# Approval & Governance Stage
#################################
  - stage: ManualValidation
    jobs:
    - job: ManualValidation
      displayName: Manual Validation
      pool: Server
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'chandanjataha1@outlook.com'
          approvers: 'chandanjataha1@outlook.com'

#################################
# Deploy: Apply Stage
#################################
  - stage: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn:
    - ManualValidation
    jobs:
    - job: Deploy
      displayName: Infra Deployment
      pool: Default
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/enviroments/dev'
          backendServiceArm: 'sp3'
          backendAzureRmStorageAccountName: 'pipelinestgaqs'
          backendAzureRmContainerName: 'tfstatecontainer'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/enviroments/dev'
          environmentServiceNameAzureRM: 'sp3'
      
      

          
          
      